apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
    {{- include "sample-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sample-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 8080
